// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using global2.NET.Database;

#nullable disable

namespace global2.NET.Database.Migrations
{
    [DbContext(typeof(FIAPDbContext))]
    partial class FIAPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceEnergyLecture", b =>
                {
                    b.Property<long>("DevicesId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("EnergyLecturesId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("DevicesId", "EnergyLecturesId");

                    b.HasIndex("EnergyLecturesId");

                    b.ToTable("DeviceEnergyLecture");
                });

            modelBuilder.Entity("global2.NET.Database.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("InovaX_Tb_Address", (string)null);
                });

            modelBuilder.Entity("global2.NET.Database.Models.ContactNumber", b =>
                {
                    b.Property<long>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PhoneId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizationAlertsId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("PhoneId");

                    b.HasIndex("OptimizationAlertsId");

                    b.ToTable("InovaX_Tb_ContactNumber", (string)null);
                });

            modelBuilder.Entity("global2.NET.Database.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DeviceStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("InovaX_Tb_Device", (string)null);
                });

            modelBuilder.Entity("global2.NET.Database.Models.EnergyLecture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Consumption")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EnergyProduction")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LectureDate")
                        .IsRequired()
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("InovaX_Tb_EnergyLecture", (string)null);
                });

            modelBuilder.Entity("global2.NET.Database.Models.IncentiveScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AcquiredScore")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("GoalAchieved")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("GoalAchievedData")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("InovaX_Tb_IncentiveScore", (string)null);
                });

            modelBuilder.Entity("global2.NET.Database.Models.OptimizationAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime?>("AlertDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("AlertDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("InovaX_Tb_OptimizationAlert", (string)null);
                });

            modelBuilder.Entity("global2.NET.Database.Models.PrincipalUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("ContactNumbersPhoneId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DevicesId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("IncentiveScoreId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactNumbersPhoneId");

                    b.HasIndex("DevicesId");

                    b.HasIndex("IncentiveScoreId");

                    b.ToTable("InovaX_Tb_User", (string)null);
                });

            modelBuilder.Entity("DeviceEnergyLecture", b =>
                {
                    b.HasOne("global2.NET.Database.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("global2.NET.Database.Models.EnergyLecture", null)
                        .WithMany()
                        .HasForeignKey("EnergyLecturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("global2.NET.Database.Models.ContactNumber", b =>
                {
                    b.HasOne("global2.NET.Database.Models.OptimizationAlert", "OptimizationAlerts")
                        .WithMany()
                        .HasForeignKey("OptimizationAlertsId");

                    b.Navigation("OptimizationAlerts");
                });

            modelBuilder.Entity("global2.NET.Database.Models.PrincipalUser", b =>
                {
                    b.HasOne("global2.NET.Database.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("global2.NET.Database.Models.ContactNumber", "ContactNumbers")
                        .WithMany()
                        .HasForeignKey("ContactNumbersPhoneId");

                    b.HasOne("global2.NET.Database.Models.Device", "Devices")
                        .WithMany()
                        .HasForeignKey("DevicesId");

                    b.HasOne("global2.NET.Database.Models.IncentiveScore", "IncentiveScore")
                        .WithMany()
                        .HasForeignKey("IncentiveScoreId");

                    b.Navigation("Address");

                    b.Navigation("ContactNumbers");

                    b.Navigation("Devices");

                    b.Navigation("IncentiveScore");
                });
#pragma warning restore 612, 618
        }
    }
}
